2023-12-01 12:36:56.328772: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudnn.so.8'; dlerror: libcudnn.so.8: cannot open shared object file: No such file or directory
2023-12-01 12:36:56.329941: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1850] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2023-12-01 12:36:56.330656: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. For example, in the saved checkpoint object, `model.layer.weight` and `model.layer_copy.weight` reference the same variable, while in the current object these are two different variables. The referenced variables are:(<keras.layers.convolutional.Conv2D object at 0x2b865a9f3a00> and <keras.layers.pooling.AveragePooling2D object at 0x2b865a756f10>).
WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. For example, in the saved checkpoint object, `model.layer.weight` and `model.layer_copy.weight` reference the same variable, while in the current object these are two different variables. The referenced variables are:(<keras.layers.core.dense.Dense object at 0x2b865a9f3fd0> and <keras.layers.core.flatten.Flatten object at 0x2b865a756370>).
WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. For example, in the saved checkpoint object, `model.layer.weight` and `model.layer_copy.weight` reference the same variable, while in the current object these are two different variables. The referenced variables are:(<keras.layers.advanced_activations.PReLU object at 0x2b865a9f3ee0> and <keras.layers.core.dense.Dense object at 0x2b865a9f3fd0>).
WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. For example, in the saved checkpoint object, `model.layer.weight` and `model.layer_copy.weight` reference the same variable, while in the current object these are two different variables. The referenced variables are:(<keras.layers.core.dense.Dense object at 0x2b865becaa00> and <keras.layers.core.dense.Dense object at 0x2b865beb5a00>).
WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. For example, in the saved checkpoint object, `model.layer.weight` and `model.layer_copy.weight` reference the same variable, while in the current object these are two different variables. The referenced variables are:(<keras.layers.core.dense.Dense object at 0x2b865bedcc10> and <keras.layers.advanced_activations.PReLU object at 0x2b865bed5640>).
WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. For example, in the saved checkpoint object, `model.layer.weight` and `model.layer_copy.weight` reference the same variable, while in the current object these are two different variables. The referenced variables are:(<keras.layers.advanced_activations.PReLU object at 0x2b865bed5640> and <keras.layers.core.dense.Dense object at 0x2b865a756d30>).
WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. For example, in the saved checkpoint object, `model.layer.weight` and `model.layer_copy.weight` reference the same variable, while in the current object these are two different variables. The referenced variables are:(<keras.layers.core.dense.Dense object at 0x2b865a756d30> and <keras.layers.advanced_activations.PReLU object at 0x2b865bed05b0>).
WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. For example, in the saved checkpoint object, `model.layer.weight` and `model.layer_copy.weight` reference the same variable, while in the current object these are two different variables. The referenced variables are:(<keras.layers.advanced_activations.PReLU object at 0x2b865bed05b0> and <keras.layers.core.reshape.Reshape object at 0x2b865bee3700>).
WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. For example, in the saved checkpoint object, `model.layer.weight` and `model.layer_copy.weight` reference the same variable, while in the current object these are two different variables. The referenced variables are:(<keras.layers.convolutional.Conv2DTranspose object at 0x2b865bf39940> and <keras.layers.advanced_activations.PReLU object at 0x2b865bf01550>).
WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. For example, in the saved checkpoint object, `model.layer.weight` and `model.layer_copy.weight` reference the same variable, while in the current object these are two different variables. The referenced variables are:(<keras.layers.advanced_activations.PReLU object at 0x2b865bf01550> and <keras.layers.convolutional.Conv2D object at 0x2b865bf40c10>).
WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. For example, in the saved checkpoint object, `model.layer.weight` and `model.layer_copy.weight` reference the same variable, while in the current object these are two different variables. The referenced variables are:(<keras.layers.convolutional.Conv2D object at 0x2b865bf40c10> and <keras.layers.advanced_activations.PReLU object at 0x2b865bf39490>).
WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. For example, in the saved checkpoint object, `model.layer.weight` and `model.layer_copy.weight` reference the same variable, while in the current object these are two different variables. The referenced variables are:(<keras.layers.advanced_activations.PReLU object at 0x2b865bf39490> and <keras.layers.advanced_activations.PReLU object at 0x2b865bf3e160>).
WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. For example, in the saved checkpoint object, `model.layer.weight` and `model.layer_copy.weight` reference the same variable, while in the current object these are two different variables. The referenced variables are:(<keras.layers.convolutional.Conv2DTranspose object at 0x2b865bf40ca0> and <keras.layers.convolutional.Conv2D object at 0x2b865bf4ca90>).
WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. For example, in the saved checkpoint object, `model.layer.weight` and `model.layer_copy.weight` reference the same variable, while in the current object these are two different variables. The referenced variables are:(<keras.layers.advanced_activations.PReLU object at 0x2b865bf3e160> and <keras.layers.advanced_activations.PReLU object at 0x2b865bf3e580>).
WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. For example, in the saved checkpoint object, `model.layer.weight` and `model.layer_copy.weight` reference the same variable, while in the current object these are two different variables. The referenced variables are:(<keras.layers.convolutional.Conv2D object at 0x2b865bf4ca90> and <keras.layers.convolutional.Conv2D object at 0x2b865bf61e80>).
Traceback (most recent call last):
  File "evaluation.py", line 114, in <module>
    curves = ad.plot.roc_per_mass(bkg_scores=scores['qcd'],
  File "/beegfs/desy/user/valentel/JointVAE4AD/ad/plot.py", line 342, in roc_per_mass
    path = utils.makedir(path + save)
  File "/beegfs/desy/user/valentel/JointVAE4AD/ad/utils.py", line 129, in makedir
    os.makedirs(path, exist_ok=True)
  File "/beegfs/desy/user/valentel/conda/envs/jvae/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/beegfs/desy/user/valentel/conda/envs/jvae/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/beegfs/desy/user/valentel/conda/envs/jvae/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/results'
